const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const {spawnSync,execFileSync} = require('node:child_process');
const plugin = path.resolve(__dirname,'..');
const ctx = vm.createContext({});
vm.runInContext(fs.readFileSync(path.join(plugin,'Pace.js'),'utf8'),ctx);
vm.runInContext(fs.readFileSync(path.join(plugin,'Upstream.js'),'utf8'),ctx);
assert.equal(ctx.classify(0,true,'current\n'),'current');
assert.equal(ctx.classify(0,true,'changed'),'changed');
for (const output of ['current','changed','','unexpected']) {
 assert.equal(ctx.classify(1,true,output),'unknown');
 assert.equal(ctx.classify(0,false,output),'unknown');
}
for (const output of ['', 'unexpected', 'current\nchanged']) assert.equal(ctx.classify(0,true,output),'unknown');
assert.equal(ctx.classify(0,true,'current'),'current');
const now = Date.parse('2026-09-17T12:00:00Z');
const day = 86400000;
const reset = new Date(now+5.125*day).toISOString();
const pace = ctx.weekly(.18,reset,now);
assert.ok(Math.abs(pace.target-1.875/7)<1e-10);
assert.equal(pace.label,'On track');
assert.equal(ctx.weekly(pace.target,reset,now).level,0);
assert.equal(ctx.weekly(pace.target+.025,reset,now).level,1);
assert.equal(ctx.weekly(pace.target+.05,reset,now).level,1);
assert.equal(ctx.weekly(pace.target+.051,reset,now).level,2);
assert.equal(ctx.weekly(1,reset,now).label,'Limit reached');
assert.equal(ctx.weekly(0,reset,now).level,0);
assert.ok(ctx.weekly(.18,reset,now+3600000).target>pace.target);
assert.equal(ctx.weekly(0,new Date(now+7*day).toISOString(),now).target,0);
for(const date of ['', 'bad',new Date(now).toISOString(),new Date(now-1).toISOString(),new Date(now+8*day).toISOString()]) assert.equal(ctx.weekly(.18,date,now),null);
for(const usage of [NaN,-1,undefined]) assert.equal(ctx.weekly(usage,reset,now),null);
const fixture=fs.mkdtempSync(path.join(os.tmpdir(),'agents-upstream-test-'));
try {
 const stock=path.join(fixture,'stock');fs.mkdirSync(stock);
 fs.writeFileSync(path.join(stock,'Panel.qml'),'original');
 const baseline=path.join(fixture,'baseline');
 const hash=execFileSync('bash',['-c',"find . -type f -print0 | LC_ALL=C sort -z | xargs -0 -r sha256sum | sha256sum | cut -d ' ' -f 1"],{cwd:stock,encoding:'utf8'});
 fs.writeFileSync(baseline,hash);
 const check=()=>execFileSync('bash',[path.join(plugin,'check-upstream'),stock,baseline],{encoding:'utf8'}).trim();
 assert.equal(check(),'current');
 fs.writeFileSync(path.join(stock,'Panel.qml'),'modified');assert.equal(check(),'changed');
 fs.writeFileSync(path.join(stock,'Panel.qml'),'original');assert.equal(check(),'current');
 fs.writeFileSync(path.join(stock,'new file'),'added');assert.equal(check(),'changed');
 fs.unlinkSync(path.join(stock,'new file'));assert.equal(check(),'current');
 fs.unlinkSync(path.join(stock,'Panel.qml'));assert.equal(check(),'changed');
 assert.notEqual(spawnSync('bash',[path.join(plugin,'check-upstream'),path.join(fixture,'missing'),baseline]).status,0);
 fs.writeFileSync(baseline,'invalid');assert.notEqual(spawnSync('bash',[path.join(plugin,'check-upstream'),stock,baseline]).status,0);
} finally {fs.rmSync(fixture,{recursive:true,force:true});}
console.log('PASS: weekly pace, color boundaries, continuous time, invalid data, and upstream change detection');
